sudo: required
language: python
python:
  - "3.8"
os:
  - linux
install:
  - pip install -r requirements.txt
script:
  - echo -e "[test]\nroot@118.24.16.115=woshigty123"
  - python oakleaf.py -h
  - python oakleaf.py get hosts
  - python oakleaf.py get hosts -g jmc
  - python oakleaf.py get groups
  - python oakleaf.py get groups -g jmc
