sudo: required
language: python
# services:
#   - docker
# addons:
#   apt:
#     packages:
#       - docker-ce
python:
  - "3.8"
os:
  - linux
install:
  - pip install -r requirements.txt
script:
  - python oakleaf.py -h
  - python oakleaf.py get hosts -a
  - python oakleaf.py get hosts -g jmc
  - python oakleaf.py get groups -a
  - python oakleaf.py get groups -g jmc
